included:
  - .   # 扫描整个项目excluded: # paths to ignore during linting. Takes precedence over `included`.

excluded:
  - .build

line_length:
  warning: 240
  ignores_function_declarations: true
  ignores_comments: true
  ignores_interpolated_strings: true
  ignores_urls: true

disabled_rules:
  - force_cast
  - force_try
  - function_body_length
  - nesting
  - todo
  - type_body_length
  - type_name
  - identifier_name
  - opening_brace
  - trailing_comma

opt_in_rules:
  - empty_count
  - first_where
  - private_action
  - private_outlet

analyzer_rules:
  - unused_import
